### ISSUE TITLE
Update failing

### ISSUE THREAD

**Issue by kwsm2m** [scowalt/chocolatey-cryptomator#2]
Hello, my update (from 1.9.2) is failing.
The error message contains: Exit code was '1603'. Exit code indicates the following: Generic MSI Error.

**Comment by scowalt** [comment]
Hey there. I would try an uninstall + reinstall if your update is failing.

A fresh install of 1.11.1 works for me, my guess is a bug in the cryptomator app itself.

Sorry I can't dive deeper 🙁 

If you want to dig further, move the conversation here, this repo is deprecated. https://github.com/scowalt/chocolatey-packages

**Comment by kwsm2m** [comment]
Hello, everything is working great now! The problem was that the old package could not be uninstalled.
This was probably because Cryptomator was set up as a start app. 
Therefore I tried to update a running program, which did not work.
